title: "NUS Tracker"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "se-edu/nus-tracker"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
